[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
via_ir = true
ffi = true
fs_permissions = [{ access = "read-write", path = "./deployments/"}]
remappings = ["@openzeppelin/=node_modules/@openzeppelin"]
auto_detect_remappings = true